config/routes.rb
Rails.application.routes.draw do

  root :to => 'tops#index'

  devise_for :users, :controllers => {
    :sessions      => "devise_custom/sessions",
    :registrations => "devise_custom/registrations",
    :passwords     => "devise_custom/passwords",
  }

  namespace :users do
    get 'home'
    resources :affiliations, only: [:create, :destroy]
  end

  resources :marks, only: [:index, :new, :create, :edit, :update, :destroy]

  resources :projects, only: [:show, :new, :create, :edit, :update] do
    resources :numbers, only: [:index, :create] do
      resources :markings, only: [:index, :create]
    end
    resources :number_formats, only: [:show, :new, :create, :edit, :update]
  end

  namespace 'api', constraints: lambda{ |request| request.format == :json } do
    namespace 'v1' do
      resources 'projects', only: [], param: :name, constraints: { name: /.*/ }  do
        resources :numbers, only: [:create]
      end
    end
  end

end

app/models/mark.rb
# == Schema Information
#
# Table name: marks
#
#  id          :integer          not null, primary key
#  owner_id    :integer
#  owner_type  :string
#  label       :string
#  description :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Mark < ActiveRecord::Base
  has_many :markings
  has_many :numbers, through: :markings

  belongs_to :owner, polymorphic: true

  validates_with MarkValidator
end

app/controllers/marks_controller.rb
class MarksController < ApplicationController
  before_action :set_mark, only: [:edit, :update, :destroy]

  # GET /marks
  # GET /marks.json
  def index
    @user_marks    = @user.marks
    @project_marks = @user.projects.map{|p| p.marks}.inject{|s, marks| s + marks}
  end

  # GET /marks/new
  def new
    @mark = Mark.new
  end

  # GET /marks/1/edit
  def edit
  end

  # POST /marks
  # POST /marks.json
  def create
    @mark = Mark.new
    if mark_params[:owner] == 'User'
      @mark.owner = @user
    else
      @mark.owner = Project.find mark_params[:owner]
    end
    @mark.label = mark_params[:label]
    @mark.description = mark_params[:description]

    respond_to do |format|
      if @mark.save
        format.html { redirect_to :action => 'index' }
        format.json { render :show, status: :created, location: @mark }
      else
        format.html { render :new }
        format.json { render json: @mark.errors, status: :bad_request}
      end
    end
  end

  # PATCH/PUT /marks/1
  # PATCH/PUT /marks/1.json
  def update
    respond_to do |format|
      if @mark.update(mark_params)
        format.html { redirect_to :action => "index" }
        format.json { render :show, status: :ok, location: @mark }
      else
        format.html { render :edit }
        format.json { render json: @mark.errors, status: :bad_request}
      end
    end
  end

  # DELETE /marks/1
  # DELETE /marks/1.json
  def destroy
    @mark.destroy
    respond_to do |format|
      format.html { redirect_to marks_url, notice: 'Mark was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mark
      @mark = Mark.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mark_params
      params.require(:mark).permit(:owner, :label, :description)
    end
end

app/helpers/marks_helper.rb
module MarksHelper
end

app/views/marks/_form.html.slim
= bootstrap_form_for @mark do |f|
    .field
        = f.text_field :label
    .field
        = f.text_field :description

    - if controller.action_name == 'new'
        = f.form_group do
            .field
                = f.radio_button     :owner,    'User',        :checked => true,      :label => 'ユーザ所有', inline: true
            - @user.projects.each do |project|
                .field
                    = f.radio_button :owner,    project.id,     :checked => false,     :label => project.name, inline: true

    .actions = f.submit '作成', :class => 'btn btn-primary'

app/views/marks/_list.html.slim
table.table
  thead
    tr
      th Label
      th Description
      th
      th 利用数
      th
      th

  tbody
    - marks.each do |mark|
      tr
        td
            p.inline.marker
                = mark.label
        td = mark.description
        td = 
        td = mark.markings.count
        td = link_to 'Edit', edit_mark_path(mark), :class => 'btn btn-primary btn-sm'
        td = link_to 'Destroy', mark, data: { confirm: 'Are you sure?' }, method: :delete, :class => 'btn btn-primary btn-sm'

app/views/marks/edit.html.slim
h1 マーク編集

== render 'form'

= link_to '戻る', marks_path, :class => 'btn btn-primary'

app/views/marks/index.html.slim
h2 個人マーク
.row
    .col-md-12
        = render partial: 'list', locals: {marks: @user_marks}

h2 プロジェクトマーク
.row
    .col-md-12
        = render partial: 'list', locals: {marks: @project_marks}

.row
    .col-md-12
        = link_to '新規作成', new_mark_path, :class => 'btn btn-primary'
.row
    .col-md-12
        = link_to '戻る', users_home_path, :class => 'btn btn-primary'

app/views/marks/new.html.slim
h1 新規マーク登録

== render 'form'

= link_to '戻る', marks_path, :class => 'btn btn-primary'