config/routes.rb
Rails.application.routes.draw do

  root :to => 'tops#index'

  devise_for :users, :controllers => {
    :sessions      => "devise_custom/sessions",
    :registrations => "devise_custom/registrations",
    :passwords     => "devise_custom/passwords",
  }

  namespace :users do
    get 'home'
    resources :affiliations, only: [:create, :destroy]
  end

  resources :marks, only: [:index, :new, :create, :edit, :update, :destroy]

  resources :projects, only: [:show, :new, :create, :edit, :update] do
    resources :numbers, only: [:index, :create] do
      resources :markings, only: [:index, :create]
    end
    resources :number_formats, only: [:show, :new, :create, :edit, :update]
  end

  namespace 'api', constraints: lambda{ |request| request.format == :json } do
    namespace 'v1' do
      resources 'projects', only: [], param: :name, constraints: { name: /.*/ }  do
        resources :numbers, only: [:create]
      end
    end
  end

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :affiliations, dependent: :destroy
  has_many :projects, through: :affiliations
  has_many :allocations
  has_many :numbers, through: :allocations, dependent: :destroy
  has_many :marks, as: :owner, dependent: :destroy

end

app/controllers/users/affiliations_controller.rb
class Users::AffiliationsController < ApplicationController
  before_action :set_affiliation, only: [:destroy]

  # POST /affiliations
  # POST /affiliations.json
  def create
    @affiliation = Affiliation.new(affiliation_params)

    respond_to do |format|
      if @affiliation.save
        format.html { redirect_to :back }
        #format.json { render :show, status: :created, location: @affiliation }
      else
        format.html { redirect_to :back }
        #format.json { render json: @affiliation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /affiliations/1
  # DELETE /affiliations/1.json
  def destroy
    @affiliation.destroy
    respond_to do |format|
      format.html { redirect_to users_home_path, notice: 'Affiliation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_affiliation
      @affiliation = Affiliation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def affiliation_params
      params.require(:affiliation).permit(:project_id, :user_id, :administrator)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def home
    @projects = Project.all
    @mark = Mark.new
  end
end

app/views/users/home.html.slim
.row
    .col-md-12
        | プロジェクト
    .col-md-12
        table.table
            thead
                tr
                    th 
            tbody
                - @projects.each do |project|
                    tr
                        td
                            .row
                                .col-md-5
                                    = project.name
                                .col-md-7
                                    - if @user.projects.include? project
                                        - affiliation = @user.affiliations.find_by(project_id: project.id)
                                        = link_to '所属解除', ['users', affiliation], method: :delete, :class => 'btn btn-primary btn-sm'
                                        = link_to '採番/設定', project, :class => 'btn btn-primary btn-sm'
                                    - else
                                        - affiliation = project.affiliations.build
                                        = bootstrap_form_for ['users', affiliation], class: 'inline-block' do |f|
                                            = f.hidden_field :project_id
                                            = f.hidden_field :user_id, :value => @user.id
                                            = f.submit '所属', :class => 'btn btn-primary btn-sm'

.row
    .col-md-12
        = link_to 'マーク設定', marks_path, :class => 'btn btn-primary btn-sm'
.row
    .col-md-12
        = link_to '新規プロジェクト', new_project_path, :class => 'btn btn-primary btn-sm'

sass:
    .new_affiliation
        display: inline
        margin-left: 4px
        margin-right: 4px

    .btn
        margin-left: 4px
        margin-right: 4px
        