config/routes.rb
Rails.application.routes.draw do

  root :to => 'tops#index'

  devise_for :users, :controllers => {
    :sessions      => "devise_custom/sessions",
    :registrations => "devise_custom/registrations",
    :passwords     => "devise_custom/passwords",
  }

  namespace :users do
    get 'home'
    resources :affiliations, only: [:create, :destroy]
  end

  resources :marks, only: [:index, :new, :create, :edit, :update, :destroy]

  resources :projects, only: [:show, :new, :create, :edit, :update] do
    resources :numbers, only: [:index, :create] do
      resources :markings, only: [:index, :create]
    end
    resources :number_formats, only: [:show, :new, :create, :edit, :update]
  end

  namespace 'api', constraints: lambda{ |request| request.format == :json } do
    namespace 'v1' do
      resources 'projects', only: [], param: :name, constraints: { name: /.*/ }  do
        resources :numbers, only: [:create]
      end
    end
  end

end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id          :integer          not null, primary key
#  name        :string
#  description :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Project < ActiveRecord::Base
  has_many :number_formats, dependent: :destroy
  has_many :affiliations, dependent: :destroy
  has_many :users, through: :affiliations
  has_many :numbers, dependent: :destroy
  has_many :marks, as: :owner, dependent: :destroy
  accepts_nested_attributes_for :marks

  validates_with ProjectValidator

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update]


  # GET /projects/1
  # GET /projects/1.json
  def show
    @marks = @project.marks + @user.marks
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
    @project.users << @user

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :bad_request }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to :action => "show" }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :bad_request }
      end
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :description)
    end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_allocation.html.slim
= bootstrap_form_for [project, Number.new] do |f|
    .col-md-12
        = f.submit '採番', :class => 'btn btn-primary btn-sm'
    .col-md-12
        table.table
            = f.form_group do
                - marks.each do |mark|
                    tr
                        td
                            = check_box_tag 'number[mark_ids][]', mark.id
                        td
                            p.inline.marker
                                = mark.label
                        td
                            = mark.description

app/views/projects/_allocation_blank.html.slim
table.table
    tr
        td
            | 番号フォーマット未登録

app/views/projects/_form.html.slim
= bootstrap_form_for @project do |f|
      .field
          = f.text_field :name
      .field
          = f.text_field :description
      .actions
          = f.submit '作成', :class => 'btn btn-primary'

app/views/projects/_formats.html.slim
table.table
    - @project.number_formats.each do |number_format|
        tr
            td.number_format
                = number_format.format
            td
                = link_to '編集', edit_project_number_format_path(@project, number_format), :class => 'btn btn-primary btn-sm'

sass:
    .number_format
        font-family: 'Roboto', 'Osaka-Mono', 'Menlo', 'ms gothic', 'monospace'
        font-size: 1.2em

app/views/projects/_formats_blank.html.slim
table.table
    tr
        td
            = link_to 'フォーマット登録', new_project_number_format_path(project), :class => 'btn btn-primary'

app/views/projects/edit.html.slim
h1 プロジェクト編集

== render 'form'

= link_to '戻る', project_path(@project), :class => 'btn btn-primary'

app/views/projects/new.html.slim
h1 新規プロジェクト

== render 'form'

= link_to '戻る', users_home_path, :class => 'btn btn-primary'

app/views/projects/show.html.slim
h1
    = @project.name
.row
    .col-md-12.project_description
        = @project.description

.row
    .col-md-12
        = link_to '編集', edit_project_path(@project), :class => 'btn btn-primary btn-sm'
        
h3 番号フォーマット
.row
    .col-md-12
        - if @project.number_formats.blank?
            = render partial: 'formats_blank', locals: {project: @project}
        - else
            = render partial: 'formats', locals: {formats: @project.number_formats}

h3 採番する
.row
    .col-md-12
        - if @project.number_formats.blank?
            = render partial: 'allocation_blank'
        - else
            = render partial: 'allocation', locals: {project: @project, marks: @marks}

h3 最近の採番
= link_to '全て見る', project_numbers_path(@project), :class => 'btn btn-primary'
.row
    .col-md-12
        = render partial: 'common/numbers', locals: {numbers: @project.numbers.last(4).reverse}

= link_to '戻る', users_home_path, :class => 'btn btn-primary'


sass:
    .project_description
        font-size: 1.5em
        border: solid 2px
        border-radius: 4px
        border-color: #a0a0a0
        background-color: #e0e0e0
        padding: 8px