config/routes.rb
Rails.application.routes.draw do

  root :to => 'tops#index'

  devise_for :users, :controllers => {
    :sessions      => "devise_custom/sessions",
    :registrations => "devise_custom/registrations",
    :passwords     => "devise_custom/passwords",
  }

  namespace :users do
    get 'home'
    resources :affiliations, only: [:create, :destroy]
  end

  resources :marks, only: [:index, :new, :create, :edit, :update, :destroy]

  resources :projects, only: [:show, :new, :create, :edit, :update] do
    resources :numbers, only: [:index, :create] do
      resources :markings, only: [:index, :create]
    end
    resources :number_formats, only: [:show, :new, :create, :edit, :update]
  end

  namespace 'api', constraints: lambda{ |request| request.format == :json } do
    namespace 'v1' do
      resources 'projects', only: [], param: :name, constraints: { name: /.*/ }  do
        resources :numbers, only: [:create]
      end
    end
  end

end

app/views/common/_numbers.html.slim
table.table.table-borderless
    thead
        tr
            th Id
            th 番号
            th ユーザ
            th 作成日時
    tbody
        - numbers.each do |number|
            tr
                td = number.id
                td = number.val
                td = number.users.first.email
                td = number.created_at_shorform
            tr
                td
                td
                    - number.marks.each do |mark|
                        p.inline.marker
                            = mark.label
                td
                    = link_to 'マーク編集', project_number_markings_path(@project, number), :class => 'btn btn-info btn-xs'

sass:
    .table-borderless tbody tr, .table-borderless tbody tr td
        border-top: none
        border-bottom: none